---
apiVersion: v1
kind: Namespace
metadata:
  name: demoapps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app-summon-init
  namespace: demoapps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app-summon-init
  name: test-app-summon-init
  namespace: demoapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-summon-init
  template:
    metadata:
      labels:
        app: test-app-summon-init
    spec:
      serviceAccountName: test-app-summon-init
      containers:
      - image: registry.cybr.com:5000/test-app:latest
        imagePullPolicy: Always
        name: test-app
        ports:
        - containerPort: 8080
        env:
          - name: CONJUR_APPLIANCE_URL
            value: https://access.dap.svc.cluster.local/api
          - name: CONJUR_ACCOUNT
            value: cyberark
          - name: CONJUR_VERSION
            value: '5'
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: k8s-app-ssl
                key: ssl-certificate
          - name: CONJUR_AUTHN_TOKEN_FILE
            value: "/run/conjur/access-token"
        resources:
          requests:
            cpu: 50m
            memory: 250Mi
          limits:
            cpu: 50m
            memory: 250Mi
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
      initContainers:
      - image: cyberark/conjur-authn-k8s-client
        imagePullPolicy: IfNotPresent
        name: authenticator
        env:
        # hardcoded values
          - name: CONTAINER_MODE
            value: init

        # values from pod metadata
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_ACCOUNT
            value: cyberark
          - name: CONJUR_VERSION
            value: '5'
          - name: CONJUR_APPLIANCE_URL
            value: https://access.dap.svc.cluster.local/api
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: k8s-app-ssl
                key: ssl-certificate
          - name: CONJUR_AUTHN_URL
            value: https://access.dap.svc.cluster.local/api/authn-k8s/k8s-follower
          - name: CONJUR_AUTHN_LOGIN
            value: host/conjur/authn-k8s/k8s-follower/apps/demoapps/service_account/test-app-summon-init
        resources:
          requests:
            cpu: 50m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 16Mi
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory